In [1]:
import cv2
import mediapipe as mp
import numpy as np
import math
import pickle

mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose

In [13]:
#set file path to the video location
path = "/Users/Philip/Documents/Humon Research Lab/fmc_COM/philip_session2_04_25_22/DataArrays/mediaPipeData_2d.npy"

In [14]:
mp_array = np.load(path)

In [21]:
len(mp_array)

3

appears to be one array for each camera

In [22]:
print(len(mp_array[0]),len(mp_array[1]),len(mp_array[2]))

4305 4305 4305


they're all the same length, which is encouraging! 

In [24]:
print(len(mp_array[0][0]), type(mp_array[0][0]))

543 <class 'numpy.ndarray'>


I'm assuming in each camera is a numpy array for each frame, containing all of the holistic face, hands, and body points (explaining why there's so many points)

There should be: 
- 33 body points
- 468 face points
- 42 hand points

We only care about the 33 body points, because those are the ones used by the center of mass script

In [26]:
print(len(mp_array[0][0][0]), type(mp_array[0][0][0]))
print(mp_array[0][0][0])

3 <class 'numpy.ndarray'>
[3.86563396e+02 1.32725276e+03 9.98229086e-01]


These are the x point, y point, and confidence value of the first camera's first frame view of the nose (mediapipe landmark 0)

In [27]:
print(mp_array[0][0][0][0])

386.5633964538574


The final structure is like this: mediaPipeData_nCams_nFrames_nImgPts_XYC 

In [29]:
landmarks = mp_array[1][213]

In [30]:
print(landmarks[15])

[1.45913246e+03 1.24446224e+03 1.05107531e-01]


In [32]:
width, height = 3840, 2160

for landmark in landmarks:
    landmark[0] /= width
    landmark[1] /= height

print(landmarks[15])

[9.89537531e-05 2.66731448e-04 1.05107531e-01]
